# Generated by Django 4.1.2 on 2022-10-30 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pelicula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=50)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.clasificacion')),
            ],
        ),
    ]
