# Generated by Django 4.1.2 on 2022-10-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=30)),
                ('plataforma', models.CharField(max_length=50)),
                ('calificacion', models.CharField(max_length=3)),
            ],
        ),
    ]
