# Generated by Django 4.1.2 on 2022-10-29 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videojuego', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pelicula',
            new_name='Videojuego',
        ),
    ]
