"""empty message

Revision ID: 06f8170001e2
Revises: 
Create Date: 2022-10-30 11:55:37.101070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f8170001e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('idAlbum', sa.Integer(), nullable=False),
    sa.Column('nombreAlbum', sa.String(length=250), nullable=True),
    sa.Column('fechaLanzamiento', sa.String(length=250), nullable=True),
    sa.Column('numCanciones', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('idAlbum')
    )
    op.create_table('cancion',
    sa.Column('idCancion', sa.Integer(), nullable=False),
    sa.Column('nombreCancion', sa.String(length=250), nullable=True),
    sa.Column('fechaEstreno', sa.String(length=250), nullable=True),
    sa.Column('discografica', sa.String(length=250), nullable=True),
    sa.Column('duracion', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('idCancion')
    )
    op.create_table('cantante',
    sa.Column('idCantante', sa.Integer(), nullable=False),
    sa.Column('nombreCantante', sa.String(length=250), nullable=True),
    sa.Column('nombreArtistico', sa.String(length=250), nullable=True),
    sa.Column('aDebut', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('idCantante')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cantante')
    op.drop_table('cancion')
    op.drop_table('album')
    # ### end Alembic commands ###
